services:
  db:
    image: kartoza/postgis:16
    environment:
      POSTGRES_DB: bulldever
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build: ./server
    volumes:
      - ./server:/app
      - /app/.venv
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/bulldever
      - DEBUG=True
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - db

  web:
    build: ./web
    volumes:
      - ./web:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api
      - WATCHPACK_POLLING=true
    depends_on:
      - server

volumes:
  postgres_data:
